<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>CS8603;CS8625;CS8600;CA2255</NoWarn>
        <DefineConstants Condition="'$(Configuration)' == 'Debug'">$(DefineConstants);FMOD_LOGGING</DefineConstants>
    </PropertyGroup> 

</Project>