<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Real.Graphics.Vulkan\Real.Graphics.Vulkan.csproj" />
      <ProjectReference Include="..\Real.Windowing.Glfw\Real.Windowing.Glfw.csproj" />
      <ProjectReference Include="..\Real\Real.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="shaders\main.frag.spv">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="shaders\main.vert.spv">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
